config/routes.rb
Rails.application.routes.draw do
  resources :vacants

  get '/postulations', to: 'postulations#index' 
  
  post '/postulations', to: 'postulations#create'

  get '/admins/new', to: 'admins#new', as: :new_user

  post '/admins', to: 'admins#create', as: :user_created

    
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "vacants#index"
end

app/models/vacant.rb
class Vacant < ApplicationRecord
  belongs_to :user
  has_many :postulations

  
end

app/controllers/vacants_controller.rb
class VacantsController < ApplicationController
  before_action :set_vacant, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]

  before_action only: [:new, :create] do
    authorize_request(["author", "admin"])
  end

  before_action only: [:edit, :update, :destroy] do
    authorize_request(["admin"])
  end
 

  # GET /vacants or /vacants.json
  def index
    @vacants = Vacant.all
  end

  # GET /vacants/1 or /vacants/1.json
  def show
    @postulation= Postulation.new
    @postulation.vacant_id = params[:id]
    @postulation.user = current_user


  end

  # GET /vacants/new
  def new
    @vacant = Vacant.new
  end

  # GET /vacants/1/edit
  def edit
  end

 

  # POST /vacants or /vacants.json
  def create
    @vacant = Vacant.new(vacant_params)
    @vacant.user_id = current_user.id

    respond_to do |format|
      if @vacant.save
        format.html { redirect_to vacant_url(@vacant), notice: "Vacant was successfully created." }
        format.json { render :show, status: :created, location: @vacant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacants/1 or /vacants/1.json
  def update
    respond_to do |format|
      if @vacant.update(vacant_params)
        format.html { redirect_to vacant_url(@vacant), notice: "Vacant was successfully updated." }
        format.json { render :show, status: :ok, location: @vacant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacants/1 or /vacants/1.json
  def destroy
    @vacant.destroy

    respond_to do |format|
      format.html { redirect_to vacants_url, notice: "Vacant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacant
      @vacant = Vacant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacant_params
      params.require(:vacant).permit(:title, :description, :salary, :user_id)
    end
end

app/helpers/vacants_helper.rb
module VacantsHelper
end

app/views/vacants/_form.html.erb
<%= form_with(model: vacant) do |form| %>
  <% if vacant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vacant.errors.count, "error") %> prohibited this vacant from being saved:</h2>

      <ul>
        <% vacant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary %>
  </div>

  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vacants/_vacant.html.erb
<div id="<%= dom_id vacant %>">
  <p>
    <strong>Title:</strong>
    <%= vacant.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= vacant.description %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= vacant.salary %>
  </p>

  

</div>

app/views/vacants/edit.html.erb
<h1>Editing vacant</h1>

<%= render "form", vacant: @vacant %>

<br>

<div>
  <%= link_to "Show this vacant", @vacant %> |
  <%= link_to "Back to vacants", vacants_path %>
</div>

app/views/vacants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vacants</h1>

<div id="vacants">
  <% @vacants.each do |vacant| %>
    <%= render vacant %>
    <p>
      <%= link_to "Show this vacant", vacant %>
    </p>
  <% end %>
</div>

<%= link_to "New vacant", new_vacant_path %>

app/views/vacants/new.html.erb
<h1>New vacant</h1>

<%= render "form", vacant: @vacant %>

<br>

<div>
  <%= link_to "Back to vacants", vacants_path %>
</div>

app/views/vacants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vacant %>

<div>

<%= form_with(model: @postulation, url: postulations_path ) do |form| %>
  <%= form.hidden_field :vacant_id %>
  <%= form.hidden_field :user_id %>
  <%= form.submit 'Postular', class:'btn btn-primary' %>

<% end %>

<%= link_to "Back to vacants", vacants_path %> 

  

<% if user_signed_in? %>
  <% if current_user.id == @vacant.user_id %>
    <%= link_to "Edit this vacant", edit_vacant_path(@vacant) %> |
    <%= button_to "Destroy this vacant", @vacant, method: :delete %>
  <% end %>
<% end %>

  
</div>