config/routes.rb
Rails.application.routes.draw do
  resources :vacants

  get '/postulations', to: 'postulations#index' 
  
  post '/postulations', to: 'postulations#create'

  get '/admins/new', to: 'admins#new', as: :new_user

  post '/admins', to: 'admins#create', as: :user_created

    
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "vacants#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <%= link_to 'Apply', vacants_path, class:'navbar-brand' %>
        <%= link_to 'Postulations', postulations_path, class:'navbar-brand' %>
        <%= link_to 'Create New User', new_user_path, class:'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <% if user_signed_in? %>
                            
                                <%= image_tag current_user.images , class:'img-user' if current_user.images.attached? %>
                            
                                <%= current_user.name %>
                            
                        <% else %>
                            registrate o conectate
                        <% end %>
                    </a>
                    <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method:
                        :delete %></li>
                        <% else %>
                            <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>